name: expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets\money.png
   - assets\medical.png
   - assets\Food.png
   - assets\Graph.png
   - assets\Category.png
   - assets\Aboutus.png
   - assets\Trash.png
   - assets\Transaction.png
   - assets\img.png
